sudo: required
language: node_js
node_js:
- '8'
services:
- docker
deploy:
  provider: script
  skip_cleanup: true
  script: bash docker_push.sh
  on:
    tags: true
env:
  global:
  - secure: PLmbWwfAtheXg+eYKxMYc8azAHmfijUnoyNpiiqtbE6LkZo0ltwIJbIyzSjtHBLD2Zne+L1MLrITRdc1g5baalLvMfuycPo6Sr0PvR2rokhBE1XyO9XKaZmHKIuEEtU4+6osbsYj7RZtz+AuLdmLTE0FLqgY0gi6nFWZyjeUOOE=
  - secure: Yk+0kfhnO/Kn5raES+DEw+JS8aPntayxj1G5Ahp6sus58ZwLbTppdjHcxEeUGkSOqF61NlTV6gJoZn+Z0F7hRncd2ULBgOF0Mgld6RkYjChUCJUBmDC+SwsbUJKCkAapefiXl4WVB/+P2v9aYtDGkvo3HyQNT3VrvL9tjOpR7Fk=
  - secure: BnH64yiw2EjmLjjg0TTR/BXuURfnTXQZnzYPeYG+8hnz1x37oN3/5evgCjXZgarhkDZUVlKc3IiV7xmRIQHeqeVcTJJHxnpyC3pfEUuDlbOEWDk9dDdJgXuLBuLjewP4brvTXFQ25EzH8NSblkZOeQ4wOb0ksLqp7v+G2W8sZIE=
