sudo: required
language: node_js
node_js:
- '8'
services:
- docker
deploy:
  provider: script
  skip_cleanup: true
  script: bash docker_push.sh
  on:
    tags: true
env:
  global:
  - secure: Rdc4V6YcgZAztqtElTYsv883Yffgci5GgG3JxtnsF96STbzdOGij2YfGGtApgq6EOmiADCpf0iENaFlAgSPWU0rZqRmwSrXm8uzuoHneIZ2p7nFt6EvUmY9qKDUUnKRMZDwYD9YcTy+JXjGsEfurgBA0ynyx6TL0DeAMRogCpX8=
  - secure: DheVVfKSox3MtRUt4CxATqp6MIcbci4+KHeRJkF/ZbcO9T5usnqtHZsFmKzF9Bv2hEMakoS2n0lKjXbOmHDwdg6rPcyYeSoldO+I4hSepIfS2gFE8pKvPNbjzHUlYYbVO1CgeMfjwyDKqnmcV6v3r4sufXQDl8yc576PkjNE1mk=
  - secure: lGeXj0PoQDGsR3+gOVJKfF1usaGNLFAAwY+sCFG9+ux+12mc2+xwJ+Fi4BEDoTINWKu5fATtKNMWIJiSwuNfFyHMZDIzPMeZAubdFBd8pQ3p72vv5HWyv3xdLfUxzURjEr4bOJ2vG6ePcTRTfBlZO0MrGCNTTZpmpDzTr2G9Xa8=
  - secure: ha1sshp3xUxlim/vci/ME5L5LmOYfzVCIuh9yfmRD3p2rJzwv6sGMnL6PTVBJQMKg4KzHWQ4hosfAfuitNhR/qPYVCf0S/AAqo2TAMzvasUwlVwPE5AeoKNv8/67kzo5gZUA7L1TE7GhK96l5xnhNfWdJwa2U1vYKOOBlShgBWA=
  - secure: JtZhKWvd1zJV/YsIixZ7exVuh8xZFmm7chobO/1IaEZ7ALQDC1byKs7xvzD7AWjQV+mX94BoLF0ZjLLDceOERcTaGpCNj5fFR3bZPQ/lwp2bQRRKhoPlu0aMpsTeFCPEAoDA2pfWlGd62z3Q+3FozN7COhPgjATOGDZqHOvtxmk=
  - secure: YZNjHUKIC0kcEnlLAr/QD8rYe0GZiGWvmqHkHag18nN2b/ZbSmvuDKF1368fnafw7Thmfi9uDvZHEclVeWVIhd/qONbM2RQcN+/DwcNrxfFcnryp39WpXQp5X5priHAU4qhHfk6z327WTSYrcoWnOkDTXhlOCkSS4yzakQ+yaEQ=
  - secure: W5xLy7mTcbghc2XNFDs2hMGtOqLLYzoT96GruNu/oXxM4CdAMRCRxysNm7s1QMDF1sobNy5Z/Z9cjF/xV0nmBgmuf3vpqCwi/EIGmLdRzadtRVM/TYo2DhJgEJ5qNK1dV/GHDM8780gj1rY4/4E8nclq7NJJMf4euGW+I7mDO70=
