sudo: required
language: node_js
node_js:
- '8'
services:
- docker
deploy:
  provider: script
  skip_cleanup: true
  script: bash deploy.sh
  on:
    tags: true
env:
  global:
  - secure: gSeNAVqRPYSljSrvADrBp1VYFKijAkplxvnMtEFbpno07JmFeiyhAsrSUmoNcRRABhXgfEwRyCIIfbzTML1jPE4+YK1XLSw8tmZowvZS8RpESAxJI8zmZRIeZ6wy3LwEa8f2GjwlBKt4XznUR8O7V27TKzg3OihUJzQ6Cn6vwdY=
  - secure: TcPAcsVmh9Xt2V55c3P69HVEeumxORIs2hR/GrEIQfm/l8aPk6gV/BC1Z7EGwxG1cK3JpIfyxnls8q4qnFO5Qfb5Ht70vc6NVZNVg0VGGPkHD9VuFT+6K0y4lVeNMZxgLC3adlOIEXNUje77RNtsV3+sy7oZemY8tkb0A0r09eI=
  - secure: JLC2soi0F8B7PMX3vz+/Cf6H2+RbIwKrAuewpqhoG7Oaka7A0WTBe3Jhe/t8rjnAxy5rkKZHVt/CtqcJwg0BYRZeJg4fYSG+Ojdt9dt5iD7yPUHQRFYXa/3otSe/58RPvs/DF9bLL7U9RoVNVFH4nI0TmAiv+g2asEsRjV8qY7w=
